### ISSUE TITLE
serverCore.lua error: "/server/data/scripts/plugins.lua:2: module 'urm_eventAnnouncements' not found

### ISSUE THREAD

**Issue by cplr** [TES3MP/server-docker#1] opened 2019-03-04 20:43 UTC
Trying to run the docker image, and I get the following error upon execution:

```
$ sudo docker run -it --name TES3MP-server -v "/volume1/docker/tes3mp:/server/data" -p "52565:25565/udp" tes3mp/server
Loading settings file: ./tes3mp-server-default.cfg
TES3MP dedicated server 0.7.0-alpha (Linux 64-bit)
Protocol version: 7
Oldest compatible commit hash: dcbc9d1831
------------------------------------------------------------
[2019-03-04 20:35:32] [ERR]: Lua script /server/data/scripts/serverCore.lua error (2): "/server/data/scripts/plugins.lua:2: module 'urm_eventAnnouncements' not found:
        no field package.preload['urm_eventAnnouncements']
        no file './urm_eventAnnouncements.lua'
        no file '/usr/share/luajit-2.1.0-beta3/urm_eventAnnouncements.lua'
        no file '/usr/local/share/lua/5.1/urm_eventAnnouncements.lua'
        no file '/usr/local/share/lua/5.1/urm_eventAnnouncements/init.lua'
        no file '/usr/share/lua/5.1/urm_eventAnnouncements.lua'
        no file '/usr/share/lua/5.1/urm_eventAnnouncements/init.lua'
        no file '/usr/share/lua/common/urm_eventAnnouncements.lua'
        no file '/usr/share/lua/common/urm_eventAnnouncements/init.lua'
        no file '/server/data/scripts/urm_eventAnnouncements.lua'
        no file '/server/data/lib/lua/urm_eventAnnouncements.lua'
        no file './urm_eventAnnouncements.so'
        no file '/usr/local/lib/lua/5.1/urm_eventAnnouncements.so'
        no file '/usr/lib/lua/5.1/urm_eventAnnouncements.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/server/data/lib/urm_eventAnnouncements.so'"
terminate called after throwing an instance of 'std::runtime_error'
  what():  Lua script /server/data/scripts/serverCore.lua error (2): "/server/data/scripts/plugins.lua:2: module 'urm_eventAnnouncements' not found:
        no field package.preload['urm_eventAnnouncements']
        no file './urm_eventAnnouncements.lua'
        no file '/usr/share/luajit-2.1.0-beta3/urm_eventAnnouncements.lua'
        no file '/usr/local/share/lua/5.1/urm_eventAnnouncements.lua'
        no file '/usr/local/share/lua/5.1/urm_eventAnnouncements/init.lua'
        no file '/usr/share/lua/5.1/urm_eventAnnouncements.lua'
        no file '/usr/share/lua/5.1/urm_eventAnnouncements/init.lua'
        no file '/usr/share/lua/common/urm_eventAnnouncements.lua'
        no file '/usr/share/lua/common/urm_eventAnnouncements/init.lua'
        no file '/server/data/scripts/urm_eventAnnouncements.lua'
        no file '/server/data/lib/lua/urm_eventAnnouncements.lua'
        no file './urm_eventAnnouncements.so'
        no file '/usr/local/lib/lua/5.1/urm_eventAnnouncements.so'
        no file '/usr/lib/lua/5.1/urm_eventAnnouncements.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/server/data/lib/urm_eventAnnouncements.so'"
```

**Comment by cplr** [comment] 2019-03-04 20:44
My config:

```
$ uname -a
Linux Syno 4.4.59+ #23824 SMP PREEMPT Tue Feb 12 16:52:55 CST 2019 x86_64 GNU/Linux synology_apollolake_418play

$ docker --version
Docker version 17.05.0-ce, build 9f07f0e-synology
```

**Comment by GrimKriegor** [comment] 2019-03-06 01:49
Thanks for reporting this.
Seems to be an issue regarding the latest changes in CoreScripts.
The devs have been notified and are working on it.
I will post here and close the issue once it has been confirmed as solved.

Meanwhile, a possible workaround would be checking out the latest working revision:
```
cd /volume1/docker/tes3mp
git fetch --unshallow
git checkout b0a77a64e6caa0b4f8e1d9ae95d49115461fd107
```

Good luck.

**Comment by GrimKriegor** [comment] 2019-03-09 01:24
This issue has been fixed upstream. Closing.

**Closed as completed by GrimKriegor** 2019-03-09 01:24 UTC
Labels: upstream
